# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetic_computation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='methods',
            field=models.TextField(blank=True),
        ),
    ]
