# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetic_computation', '0002_auto_20190217_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin_link',
            field=models.URLField(blank=True),
        ),
    ]
